### PR TITLE
Strategy pattern

### PR DESCRIPTION
**Pull request by karencalpo**
Not checking into master yet. I just need you to check my current refactor effort.

### CODE REVIEW

**Comment by karencalpo** [comment]
You can just close the pull request once you are done reviewing. Not ready to merge with master yet.

**Comment by karencalpo** [comment]
Please check and merge with master as discussed.

**Comment by thedocbwarren** [comment]
Looks good!

**Comment by thedocbwarren** [comment]
Need to create a data model (object) for the parameters for send to the requestor.

**Comment by thedocbwarren** [comment]
basically refactor this:

const fema_url = encodeURI(`/api/open/v1/DisasterDeclarationsSummaries?$filter=${filter}&$orderby=fyDeclared,state,declaredCountyArea,fyDeclared`);
    const properties_url = encodeURI(`/propertyapi/v1.0.0/assessment/snapshot?address1=${req.query.address}&address2=${req.query.city}&radius=${radius}&pageSize=${pageSize}&page=${page}&orderBy=assdttlvalue+desc`);

    ATTOMconstants.attom_properties_data["path"] = properties_url;
    ATTOMconstants.fema_data["path"] = fema_url;

    const headers = [ATTOMconstants.attom_properties_data, ATTOMconstants.fema_data];

to move to data object vs using hard coded constants.

**Pull request merged**
